let responses = {
    // SAUDAÇÃO:
    "oi": "Oi! Como posso ajudar você hoje?",
    "olá": "Olá! Em que posso ser útil?",
    "tchau": "Tchau! Tenha um ótimo dia!",
    "bom dia": "Bom dia! Como você está?",
    "boa tarde": "Boa tarde! Espero que seu dia esteja indo bem.",
    "boa noite": "Boa noite! Precisa de alguma coisa antes de dormir?",
    "até logo": "Até logo! Foi bom falar com você.",

    // ASSUNTOS GERAIS:
    "clima": "Hoje está ensolarado com algumas nuvens.",
    "notícias": "As principais notícias do dia são sobre política e economia.",
    "trânsito": "O trânsito está congestionado na avenida principal.",
    "esporte": "O time local ganhou o último jogo por 2 a 0.",
    "entretenimento": "Estreou um novo filme no cinema que está fazendo sucesso.",
    "saúde": "É importante manter uma dieta equilibrada e praticar exercícios regularmente.",
    "viagem": "Planejo fazer uma viagem para a praia no próximo fim de semana.",
    "comida": "Hoje vou preparar um prato de massa com molho pesto para o jantar.",
    "tecnologia": "A nova versão do smartphone será lançada no próximo mês.",
    "educação": "É fundamental investir na educação para o desenvolvimento pessoal.",
    "finanças": "É recomendável fazer um planejamento financeiro para alcançar seus objetivos.",
    "amor": "O mais importante em um relacionamento é a comunicação e o respeito mútuo.",
    "filmes": "Recomendo assistir ao filme que ganhou o Oscar este ano.",
    "livros": "Estou lendo um romance histórico que é muito envolvente.",
    "arte": "Visitei uma exposição de arte contemporânea na semana passada.",
    "moda": "As tendências de moda deste ano destacam cores vibrantes e estampas florais.",
    "casa": "Estou redecorando meu apartamento para torná-lo mais acolhedor.",
    "animais": "Tenho um cachorro e um gato como animais de estimação.",
    "jogos": "O novo jogo de aventura foi lançado e está recebendo ótimas críticas.",
    "carreira": "Estou em busca de novas oportunidades de crescimento profissional.",
    "música": "Minha banda favorita vai fazer um show na cidade no próximo mês.",
    "família": "A família é a base de tudo e deve ser valorizada sempre.",
    "amizade": "Os amigos são essenciais para compartilhar momentos e experiências.",
    "viagens": "Explorar novos lugares é uma das minhas paixões.",
    "exercícios": "Praticar exercícios físicos é fundamental para manter a saúde em dia.",
    "saúde mental": "Cuidar da saúde mental é tão importante quanto cuidar da saúde física.",
    "hobbies": "Meus hobbies incluem fotografia, jardinagem e culinária.",
    "eventos": "Participei de um evento cultural muito interessante no fim de semana.",
    "teatro": "Assisti a uma peça de teatro emocionante no último mês.",
    "cinema": "O novo filme de ação está fazendo muito sucesso nas bilheterias.",
    "estudos": "Estou fazendo um curso online para aprimorar minhas habilidades.",
    "compras": "Fiz algumas compras online para renovar meu guarda-roupa.",
    "economia": "A economia está mostrando sinais de recuperação após o período de recessão.",
    "política": "As últimas decisões políticas estão gerando debates intensos na sociedade.",
    "arte": "Admiro pinturas clássicas e obras de arte contemporânea.",
    "religião": "A religião desempenha um papel importante na vida de muitas pessoas.",
    
    // TECNOLOGIA E ROBÓTICA:
    "inteligência artificial": "A inteligência artificial está avançando rapidamente e impactando diversas indústrias.",
    "internet das coisas": "A Internet das Coisas (IoT) está conectando dispositivos do dia a dia à internet.",
    "5G": "A tecnologia 5G promete revolucionar a velocidade e a confiabilidade das redes móveis.",
    "veículos autônomos": "Veículos autônomos estão em fase de testes e podem se tornar comuns em breve.",
    "impressão 3D": "Impressão 3D está transformando a fabricação de peças personalizadas.",
    "realidade aumentada": "A realidade aumentada (AR) está sendo utilizada em aplicativos móveis e jogos.",
    "blockchain": "Blockchain está sendo explorado para melhorar a segurança e a transparência em transações.",
    "drones": "Drones estão sendo usados para entrega de pacotes e serviços de emergência.",
    "assistentes virtuais": "Assistentes virtuais como Alexa e Google Assistant estão se tornando cada vez mais inteligentes.",
    "carros elétricos": "Os carros elétricos estão se tornando mais acessíveis e populares.",
    "cibersegurança": "A cibersegurança é uma preocupação crescente com o aumento das ameaças online.",
    "computação em nuvem": "A computação em nuvem está facilitando o armazenamento e processamento de grandes volumes de dados.",
    "robôs industriais": "Robôs estão sendo cada vez mais utilizados na automação industrial.",
    "próteses robóticas": "Os avanços na robótica estão permitindo a criação de próteses mais funcionais para pessoas com deficiência.",
    "cirurgias robóticas": "A robótica está transformando a forma como fazemos cirurgias, tornando-as menos invasivas.",
    "robôs de serviço": "Os robôs de serviço estão começando a aparecer em hotéis e restaurantes para ajudar no atendimento.",
    "exploração robótica": "Pesquisadores estão desenvolvendo robôs para explorar ambientes extremos, como o fundo do mar e o espaço.",

    // CIÊNCIA:
    "astronomia": "A astronomia nos ajuda a entender melhor o universo e nosso lugar nele.",
    "física": "A física estuda as leis fundamentais que governam o comportamento da matéria e da energia.",
    "química": "A química investiga a composição, estrutura e propriedades das substâncias e as mudanças que elas sofrem.",
    "biologia": "A biologia estuda os seres vivos e os processos vitais.",
    "geologia": "A geologia analisa a composição, estrutura e processos da Terra.",
    "ecologia": "A ecologia examina as relações entre os organismos e seu ambiente.",
    "genética": "A genética estuda a hereditariedade e a variação nos organismos.",
    "medicina": "A medicina utiliza o conhecimento científico para diagnosticar e tratar doenças.",
    "neurociência": "A neurociência investiga o sistema nervoso e o funcionamento do cérebro.",
    "psicologia": "A psicologia explora a mente humana e o comportamento.",
    "climatologia": "A climatologia estuda os padrões climáticos e suas mudanças ao longo do tempo.",
    "oceanografia": "A oceanografia explora os oceanos e seus fenômenos.",
    "paleontologia": "A paleontologia estuda os fósseis e a história da vida na Terra.",
    "antropologia": "A antropologia examina as culturas humanas e sua evolução.",
    "arqueologia": "A arqueologia investiga as sociedades antigas através de suas ruínas e artefatos.",
    "cosmologia": "A cosmologia estuda a origem e evolução do universo.",
    "bioquímica": "A bioquímica analisa os processos químicos que ocorrem nos organismos vivos.",
    "microbiologia": "A microbiologia estuda os microorganismos e suas interações com outros seres vivos.",
    "zoologia": "A zoologia investiga os animais e seu comportamento.",
    "botânica": "A botânica estuda as plantas e suas propriedades.",

    // FILOSOFIA:
    "ética": "A ética investiga os princípios que orientam o comportamento humano e a distinção entre o certo e o errado.",
    "metafísica": "A metafísica explora a natureza da realidade, da existência e do ser.",
    "epistemologia": "A epistemologia estuda a natureza e os limites do conhecimento.",
    "lógica": "A lógica examina os princípios do raciocínio válido e da argumentação.",
    "estética": "A estética investiga a natureza da beleza e da arte.",
    "filosofia política": "A filosofia política analisa os fundamentos do governo e da justiça.",
    "filosofia da mente": "A filosofia da mente estuda a natureza da mente e sua relação com o corpo.",
    "existencialismo": "O existencialismo explora a liberdade individual, a responsabilidade e o sentido da vida.",
    "niilismo": "O niilismo questiona o valor e o significado da existência.",
    "pragmatismo": "O pragmatismo enfatiza a prática e os resultados como critério para a verdade.",
    "idealismo": "O idealismo afirma que a realidade é fundamentalmente mental ou espiritual.",
    "realismo": "O realismo sustenta que os objetos existem independentemente da percepção humana.",
    "utilitarismo": "O utilitarismo avalia a moralidade com base na maximização do bem-estar.",
    "deontologia": "A deontologia enfatiza o dever e as regras morais como base da ética.",
    "humanismo": "O humanismo valoriza a dignidade humana e a capacidade de auto-realização.",
    "filosofia oriental": "A filosofia oriental inclui tradições como o confucionismo, taoísmo e budismo, que abordam a harmonia, a sabedoria e a iluminação.",
    "filosofia continental": "A filosofia continental abrange movimentos como o existencialismo, fenomenologia e pós-estruturalismo.",
    "filosofia analítica": "A filosofia analítica foca na clareza lógica e na análise linguística.",
    "hermenêutica": "A hermenêutica estuda a interpretação de textos, especialmente em contextos filosóficos e religiosos.",

    // TEOLOGIA:
    "cristianismo": "O cristianismo é centrado na vida e nos ensinamentos de Jesus Cristo.",
    "teologia bíblica": "A teologia bíblica estuda os textos sagrados da Bíblia e seu significado.",
    "teologia sistemática": "A teologia sistemática organiza e interpreta as doutrinas fundamentais da fé cristã.",
    "teologia moral": "A teologia moral examina os princípios éticos à luz da fé religiosa.",
    "escatologia": "A escatologia trata das questões relacionadas ao fim dos tempos e à vida após a morte.",
    "teologia pastoral": "A teologia pastoral foca na aplicação prática das crenças religiosas no cuidado das comunidades.",
    "trindade": "A doutrina da Trindade descreve Deus como três pessoas em um único ser: Pai, Filho e Espírito Santo.",
    "soteriologia": "A soteriologia estuda a doutrina da salvação.",
    "eclesiologia": "A eclesiologia examina a natureza e a estrutura da Igreja.",
    "pneumatologia": "A pneumatologia estuda o Espírito Santo e sua obra.",
    "angelologia": "A angelologia estuda os anjos e sua função na teologia.",
    "hamartiologia": "A hamartiologia investiga a natureza do pecado e suas consequências.",
    "teologia natural": "A teologia natural busca compreender Deus através da razão e da observação do mundo natural.",
    "revelação": "A doutrina da revelação trata de como Deus se comunica com a humanidade.",
    "teodiceia": "A teodiceia explora a questão do mal e do sofrimento em um mundo criado por um Deus bom e onipotente.",
    "teologia comparada": "A teologia comparada analisa as semelhanças e diferenças entre diversas tradições religiosas.",
    "liturgia": "A liturgia envolve os rituais e práticas de adoração na religião.",
    "hermenêutica bíblica": "A hermenêutica bíblica foca na interpretação e exegese das Escrituras.",
    "missiologia": "A missiologia estuda a missão da Igreja e a evangelização.",

    // PROGRAMAÇÃO:
    "algoritmos": "Algoritmos são conjuntos de instruções que resolvem problemas ou realizam tarefas específicas.",
    "linguagens de programação": "Existem várias linguagens de programação, como Python, JavaScript, Java e C++.",
    "estruturas de dados": "Estruturas de dados, como listas, filas e árvores, são usadas para organizar e manipular informações.",
    "programação orientada a objetos": "A programação orientada a objetos utiliza conceitos como classes e objetos para estruturar o código.",
    "desenvolvimento web": "O desenvolvimento web inclui a criação de sites e aplicações web usando tecnologias como HTML, CSS e JavaScript.",
    "banco de dados": "Bancos de dados armazenam e gerenciam dados, e podem ser relacionais (SQL) ou não relacionais (NoSQL).",
    "debugging": "Debugging é o processo de identificar e corrigir erros no código.",
    "integração contínua": "Integração contínua é uma prática que envolve a fusão frequente de alterações de código em um repositório compartilhado.",
    "versionamento": "O versionamento usa sistemas como Git para rastrear mudanças no código ao longo do tempo.",
    "testes de software": "Testes de software garantem que o código funcione corretamente e ajudem a identificar falhas antes da produção.",
    "API": "Uma API (Interface de Programação de Aplicações) permite que diferentes softwares se comuniquem e troquem dados.",
    "frameworks": "Frameworks são conjuntos de ferramentas e bibliotecas que ajudam a simplificar o desenvolvimento de aplicações.",
    "programação funcional": "A programação funcional é um paradigma que trata funções como cidadãos de primeira classe e evita efeitos colaterais.",
    "programação concorrente": "Programação concorrente lida com a execução de múltiplas tarefas simultaneamente, aumentando a eficiência.",
    "segurança de software": "Segurança de software envolve práticas para proteger o código contra vulnerabilidades e ataques.",
    "design patterns": "Design patterns são soluções reutilizáveis para problemas comuns no desenvolvimento de software.",
    "machine learning": "Machine learning é um ramo da programação que se concentra em criar sistemas que aprendem e melhoram com dados.",
    "devops": "DevOps é uma abordagem que integra o desenvolvimento e as operações para melhorar a colaboração e a eficiência na entrega de software.",
    "programação web": "A programação web envolve o desenvolvimento de sites e aplicativos acessíveis pela internet, utilizando front-end e back-end.",

    // VOCÊ PODE ADICIONAR MUITO MAIS DIALOGOS...

    // CASO DÊ ELSE:
    "default": "Desculpe, não tenho uma resposta para essa pergunta. Pode tentar outra?"
}
