let responses = {
    "clima": "Hoje está ensolarado com algumas nuvens.",
    "notícias": "As principais notícias do dia são sobre política e economia.",
    "trânsito": "O trânsito está congestionado na avenida principal.",
    "esporte": "O time local ganhou o último jogo por 2 a 0.",
    "entretenimento": "Estreou um novo filme no cinema que está fazendo sucesso.",
    "saúde": "É importante manter uma dieta equilibrada e praticar exercícios regularmente.",
    "viagem": "Planejo fazer uma viagem para a praia no próximo fim de semana.",
    "comida": "Hoje vou preparar um prato de massa com molho pesto para o jantar.",
    "tecnologia": "A nova versão do smartphone será lançada no próximo mês.",
    "educação": "É fundamental investir na educação para o desenvolvimento pessoal.",
    "finanças": "É recomendável fazer um planejamento financeiro para alcançar seus objetivos.",
    "amor": "O mais importante em um relacionamento é a comunicação e o respeito mútuo.",
    "filmes": "Recomendo assistir ao filme que ganhou o Oscar este ano.",
    "livros": "Estou lendo um romance histórico que é muito envolvente.",
    "arte": "Visitei uma exposição de arte contemporânea na semana passada.",
    "moda": "As tendências de moda deste ano destacam cores vibrantes e estampas florais.",
    "casa": "Estou redecorando meu apartamento para torná-lo mais acolhedor.",
    "animais": "Tenho um cachorro e um gato como animais de estimação.",
    "jogos": "O novo jogo de aventura foi lançado e está recebendo ótimas críticas.",
    "carreira": "Estou em busca de novas oportunidades de crescimento profissional.",
    "música": "Minha banda favorita vai fazer um show na cidade no próximo mês.",
    "família": "A família é a base de tudo e deve ser valorizada sempre.",
    "amizade": "Os amigos são essenciais para compartilhar momentos e experiências.",
    "viagens": "Explorar novos lugares é uma das minhas paixões.",
    "exercícios": "Praticar exercícios físicos é fundamental para manter a saúde em dia.",
    "saúde mental": "Cuidar da saúde mental é tão importante quanto cuidar da saúde física.",
    "hobbies": "Meus hobbies incluem fotografia, jardinagem e culinária.",
    "eventos": "Participei de um evento cultural muito interessante no fim de semana.",
    "teatro": "Assisti a uma peça de teatro emocionante no último mês.",
    "cinema": "O novo filme de ação está fazendo muito sucesso nas bilheterias.",
    "estudos": "Estou fazendo um curso online para aprimorar minhas habilidades.",
    "compras": "Fiz algumas compras online para renovar meu guarda-roupa.",
    "economia": "A economia está mostrando sinais de recuperação após o período de recessão.",
    "política": "As últimas decisões políticas estão gerando debates intensos na sociedade.",
    "arte": "Admiro pinturas clássicas e obras de arte contemporânea.",
    "religião": "A religião desempenha um papel importante na vida de muitas pessoas.",
    "default": "Desculpe, não tenho uma resposta para essa pergunta. Pode tentar outra?"
}
